import { ArrowRight, ArrowUpRight, ArrowLeft, BookOpen, Linkedin, Mail } from 'lucide-react';
import { Hero } from '@/components/ui/animated-hero';
import TactileHighlight from '@/components/ui/tactile-highlight';
import { ContainerScroll } from '@/components/ui/container-scroll-animation';
import { Button } from '@/components/ui/button';
import { articles, profile } from './content';

const base = import.meta.env.BASE_URL;
const route = decodeURI(window.location.pathname).replace(base, '').replace(/index\.html$/, '').replace(/\/$/, '');
const article = articles.find(a => route === `articulos/${a.slug}`);
const active = route.startsWith('articulos') ? 'articulos' : route === 'sobre-mi' ? 'sobre-mi' : '';

function ArticleList() {
  return <div className="article-list">{articles.map((item, index) => <a className="article-row" key={item.slug} href={`${base}articulos/${item.slug}/`}><span className="article-number">0{index + 1}</span><h3>{item.title}</h3><ArrowUpRight className="article-arrow" size={23} /></a>)}</div>;
}

function Contact() {
  return <section className="contact" id="contacto"><div><p className="eyebrow">SIGAMOS LA CONVERSACIÓN</p><h2>Las buenas ideas<br />empiezan hablando.</h2></div><div className="contact-right"><p>¿Tienes una pregunta, una idea o quieres saber más sobre mis clases? Me encantará leerte.</p><div className="contact-links"><a href={profile.linkedin} target="_blank" rel="noreferrer"><Linkedin size={17} /> LinkedIn <ArrowUpRight size={16} /></a>{profile.email && <a href={`mailto:${profile.email}`}><Mail size={17} /> Gmail <ArrowUpRight size={16} /></a>}</div></div></section>;
}

function Home() {
  return <><Hero base={base} /><section className="home-articles"><div className="section-top"><div><p className="eyebrow">PARA EMPEZAR A LEER</p><h2>Una idea puede cambiar<br />tu forma de ver las cosas.</h2></div><a className="text-link" href={`${base}articulos/`}>Todos los artículos <ArrowUpRight size={16} /></a></div><ArticleList /></section>
    <section className="about-teaser"><div><p className="eyebrow">DETRÁS DE ESTAS LÍNEAS</p><h2>Hola, soy Íñigo.</h2></div><div><p>De la auditoría financiera al estudio del aprendizaje, hay una pregunta que me acompaña: ¿cómo podemos entender mejor lo que hacemos?</p><p>Este es mi espacio para compartir lo que voy descubriendo. Ideas sencillas, preguntas abiertas y herramientas para llevar la teoría a la práctica.</p><a className="text-link" href={`${base}sobre-mi/`}>Conoce mi historia <ArrowUpRight size={16} /></a></div></section>
    <ContainerScroll titleComponent={<><p className="eyebrow">DE LA TEORÍA A LA PRÁCTICA</p><h2>No solo aprender más.<br /><TactileHighlight>Aprender mejor.</TactileHighlight></h2></>}><div className="study-card-top"><span><BookOpen size={17} /> NOTAS SOBRE APRENDIZAJE</span><span>01</span></div><div className="study-card-body"><span className="handwritten">Una idea para hoy</span><h3>Cierra el libro.<br />Abre una pregunta.</h3><p>Intenta explicar lo que acabas de aprender<br className="desktop-break" /> sin mirar tus apuntes.</p><a href={`${base}articulos/aprender-sin-releer/`} className="text-link">Descubre el recuerdo activo <ArrowUpRight size={17} /></a></div><div className="study-card-bottom"><span>ENTENDER → RECORDAR → APLICAR</span><span>ÍÑIGO ATELA</span></div></ContainerScroll><Contact /></>;
}

function Articles() {
  return <><section className="page-heading"><p className="eyebrow">IDEAS QUE MERECE LA PENA EXPLORAR</p><h1>Artículos<span className="accent">.</span></h1><p>Sobre aprender mejor, pensar con claridad y tomar decisiones.<br className="desktop-break" /> Sin fórmulas mágicas. Con curiosidad y ganas de ponerlo en práctica.</p></section><section className="archive"><div className="archive-label"><span>TODOS LOS ARTÍCULOS</span><span>02 TEXTOS</span></div><ArticleList /><p className="archive-note">Un pequeño archivo que irá creciendo, idea a idea.</p></section><Contact /></>;
}

function About() {
  return <><section className="page-heading about-heading"><p className="eyebrow">UN POCO SOBRE MÍ</p><h1>Hola, soy Íñigo Atela<span className="accent">.</span></h1><p>Estudiante por vocación.<br />Curioso por naturaleza.</p></section><div className="about-layout"><aside className="about-aside"><div className="monogram" aria-label="Iniciales de Íñigo Atela">ía<span>.</span></div><p>Íñigo Atela Navarro</p><span>APRENDIZAJE · EMPRESA · DECISIONES</span><a className="text-link" href={profile.linkedin} target="_blank" rel="noreferrer">Nos vemos en LinkedIn <ArrowUpRight size={15} /></a></aside><div className="about-prose"><section><p className="eyebrow">01 — MI RECORRIDO</p><h2>Siempre al otro lado<br />de una nueva pregunta.</h2><p>Actualmente estudio un máster en Internacionalización de Empresas en la Universidad Internacional Menéndez Pelayo (UIMP).</p><p>Antes estudié el grado en Administración y Dirección de Empresas y trabajé durante cerca de dos años en el departamento de auditoría financiera de PricewaterhouseCoopers (PwC).</p><p>Después estudié y aprobé el examen CFA Level I, el primer nivel de una certificación de finanzas. Prepararlo me hizo dedicar tiempo no solo a lo que estudiaba, sino también a cómo lo estudiaba.</p><div className="journey"><div><span>AHORA</span><strong>Internacionalización de Empresas</strong><p>Máster · UIMP</p></div><div><span>FORMACIÓN</span><strong>CFA Level I aprobado</strong><p>Finanzas y análisis</p></div><div><span>EXPERIENCIA</span><strong>Auditoría financiera</strong><p>PwC · Cerca de 2 años</p></div><div><span>EL PUNTO DE PARTIDA</span><strong>Administración y Dirección de Empresas</strong><p>Grado universitario</p></div></div></section><section><p className="eyebrow">02 — CÓMO PUEDE AYUDARTE MI TRABAJO</p><h2>Aprender también<br />se aprende.</h2><p>Durante mi trayectoria he invertido gran parte de mi tiempo en estudiar nuevos temas y conceptos. Esa experiencia me ha llevado a interesarme por la ciencia que hay detrás del aprendizaje.</p><p>¿Por qué recordamos algunas cosas y olvidamos otras? ¿Cómo podemos estudiar de una manera más consciente? Conceptos como el <strong>recuerdo activo</strong> y la <strong>repetición espaciada</strong> ofrecen un buen punto de partida.</p><p>En esta página y en mis clases a estudiantes comparto cómo aplicar estas ideas. El objetivo es sencillo: <TactileHighlight>aprender a aprender.</TactileHighlight></p><p>Espero que encuentres aquí algo que puedas usar en tu próxima sesión de estudio, en una decisión o en una conversación.</p><Button asChild><a href={`${base}articulos/`}>Empieza por un artículo <ArrowRight size={16} /></a></Button></section></div></div><Contact /></>;
}

function Article() {
  if (!article) return null;
  const next = articles.find(a => a.slug !== article.slug)!;
  return <><article className="reading-page"><a className="text-link back-link" href={`${base}articulos/`}><ArrowLeft size={16} /> Todos los artículos</a><header><p className="eyebrow">{article.topic.toUpperCase()} <span className="meta-dot">/</span> {article.time.toUpperCase()} DE LECTURA</p><h1>{article.title}</h1><p className="article-intro">{article.intro}</p><div className="byline"><span className="small-monogram">ía.</span><span>Íñigo Atela <span className="byline-detail">Notas para llevar a la práctica</span></span></div></header><div className="article-body">{article.sections.map(section => <section key={section.heading}><h2>{section.heading}</h2>{section.paragraphs.map(p => <p key={p}>{p}</p>)}</section>)}<blockquote><span>UNA IDEA PARA LLEVARTE</span>{article.takeaway}</blockquote>{article.source && <p className="source-note">Para profundizar: <a href={article.source.url} target="_blank" rel="noreferrer">{article.source.label} ↗</a>.</p>}</div><div className="next-article"><p className="eyebrow">SIGUE EXPLORANDO</p><a href={`${base}articulos/${next.slug}/`}>{next.title} <ArrowUpRight size={24} /></a></div></article></>;
}

export function App() {
  const knownRoute = route === '' || route === 'articulos' || route === 'sobre-mi' || !!article;
  return <><a className="skip-link" href="#contenido">Saltar al contenido</a><div className="site-shell"><header className="site-header"><a className="wordmark" href={base} aria-label="Íñigo Atela — Home">íñigo atela<span>.</span></a><nav aria-label="Navegación principal">{[['', 'Home'], ['articulos', 'Artículos'], ['sobre-mi', 'Sobre mí']].map(([path, label]) => <a key={label} href={`${base}${path ? `${path}/` : ''}`} aria-current={active === path ? 'page' : undefined}>{label}</a>)}</nav><a className="header-contact" href="#contacto">Hablemos <ArrowUpRight size={15} /></a></header><main id="contenido">{article ? <Article /> : route === 'articulos' ? <Articles /> : route === 'sobre-mi' ? <About /> : knownRoute ? <Home /> : <section className="page-heading"><h1>Esta página no existe.</h1><a href={base} className="text-link">Volver a Home <ArrowRight size={17} /></a></section>}{article && <Contact />}</main><footer><a className="wordmark" href={base}>íñigo atela<span>.</span></a><p>Siempre aprendiendo. Siempre compartiendo.</p><span>© {new Date().getFullYear()} Íñigo Atela</span></footer></div></>;
}
